# Generated by Django 3.0.6 on 2020-09-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humidityreading',
            old_name='uid',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='temperaturereading',
            old_name='uid',
            new_name='device',
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
