# Generated by Django 3.0.6 on 2020-09-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20200905_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uid',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
